### ISSUE TITLE
PUT vs POST

### ISSUE THREAD

**Issue by rancid2040** [Jrokisky/go_simple_rest#12]
Reading from the [web url](http://www.drdobbs.com/web-development/restful-web-services-a-tutorial/240169069?pgno=2): he mentions PUT vs. POST to be the same on edit, but different on creation, ie POST means always make a new resource, where PUT means the user provides the URI (which can create or edit).  Should we support POST as described by this document?  I think we could, but this sort of doesn't make sense as we use the name and label as identifiers - I guess they can not supply one, and we create and track a history of used names?  I'm not sure this is in the scope.

If we decide to do this, I think we can change our API to only understand PUT on the resource itself, like sites/$SITE and sites/$SITE/accesspoint/$AP, and say POST is valid on the resource type, like sites/ and site/$SITE/accesspoints where the logic checks the name or label (if it exists, can they supply empty names that we fill in?) and creates the resource.

What do you think?  We could simply describe in the README what we support, and how our functions work.

**Comment by rancid2040** [comment]
Hmm.. thinking of simplicity, and based on your TODO [here](https://github.com/Jrokisky/go_simple_rest/blob/master/simple-rest.go#L56): I think it might be simpler to make POST/PUT be on the resource type, like sites/ and sites/$SITE/accesspoints so we avoid entirely the need to match url and name/label inside the POST.  Then, we can have only GET to be on resource id like sites/$SITE and sites/$SITE/accesspoints/$AP.

**Comment by Jrokisky** [comment]
That sounds good to me. I don't think there will be too much lift associated with it either.

**Comment by Jrokisky** [comment]
pr up
