### ISSUE TITLE
[High Priority] Implement editing Sites

### ISSUE THREAD

**Issue by Jrokisky** [Jrokisky/go_simple_rest#2]
Need to add an endpoint and function that allows for sites to be edited.

Not sure if names should be editable.

**Comment by rancid2040** [comment]
From the description, I read it as site attributes are affected by CRUD, and the name is an attribute.

**Comment by Jrokisky** [comment]
For edits, if there's a name change, I think we can delete the old file with the old name, and create a new file with the new name.
Im going to include the work for this on the same branch as the delete op due to this.
