### ISSUE TITLE
[High priority] Implement deleting Sites

### ISSUE THREAD

**Issue by Jrokisky** [Jrokisky/go_simple_rest#3]
The delete should cascade to all associated access points.

I think we should be able to save access points in the same file as the site, and just delete that file.

Need to see how the Go Json lib handles referenced entities.

**Comment by rancid2040** [comment]
That seems like a clean solution.

In terms of referenced entities, you mean:

```go
type Site struct {
	Name string
	Role string
	Uri string
	Access_points []AccessPoint // <--- this?
}
```

**Comment by Jrokisky** [comment]
yup!

**Comment by Jrokisky** [comment]
PR will be up soon.
