### ISSUE TITLE
[High Priority] Implement Creating Access Points

### ISSUE THREAD

**Issue by Jrokisky** [Jrokisky/go_simple_rest#4]
Assuming access points should be created on the path of the site that they belong to.

Ex: /sites/$SITE_NAME/accesspoints/create

Need to run validation logic to ensure that we do not create duplicate (same label) access points

**Comment by rancid2040** [comment]
That looks right to me, where a GET request would be
/sites/$SITE_NAME/accesspoints/$AP_LABEL
